//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class habit_logs
    {
        public int id { get; set; }
        public int habit_id { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
    
        public virtual habits habits { get; set; }
    }
}
